name: Render Deployment
on: 
  push:
    tags: ['v*.*.*']

jobs:
  Render-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Render backend deployment
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_BACKEND_URL }}
        run: 
          curl "$deploy_url"

      - name: Render frontend deployment
        env: 
          deploy_url: ${{ secrets.RENDER_DEPLOY_FRONTEND_URL }}
        run: 
          curl "$deploy_url"

# health check added /api/health but there's no settings for it and notifications are for failing